# Generated by Django 4.1.2 on 2022-10-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=80)),
                ("sale_status", models.CharField(default="W", max_length=1)),
                ("is_sale", models.IntegerField(default=0)),
                ("desc_context", models.TextField()),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductImg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("thumbnail", models.CharField(max_length=255)),
                ("detail_img", models.JSONField()),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_img",
            },
        ),
        migrations.CreateModel(
            name="ProductDescription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("package", models.CharField(max_length=50)),
                ("producer", models.CharField(max_length=100)),
                ("product_date", models.DateField()),
                ("expire_date", models.DateField()),
                ("law_info", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("storage_method", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_description",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.PositiveIntegerField(default=0)),
                ("delivery_fee", models.PositiveIntegerField(default=0)),
                ("options", models.JSONField(default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "cart",
            },
        ),
    ]
