databases:
  host: "host url"
  port: 3306
  database: "db name"
  username: "username"
  password: "passwd"
  timezone: "+09:00"

secrets:
  django: "django-something-something"


naver_pay:
  client_id: "some id"
  mode: "production or develop"
  merchantUserKey: 1234
  merchantPayKey: 1234

card_pay:
  member_id: 1234

token:
  scret: "JWT SECRET HERE"